allow-flight=true
enable-command-block=true
gamemode=creative
online-mode=false
level-type=minecraft\:flat
generate-structures=false
generator-settings={"layers"\:[{"block"\:"minecraft\:air","height"\:1}],"biome"\:"minecraft\:the_void"}
